[build]
  command = "cd app && npm install"
  publish = "app/public"
  functions = "app/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["youtube-dl-exec"]
  included_files = ["app/node_modules/youtube-dl-exec/bin/**"]

[functions."list-videos"]
  timeout = 26

[functions."transcript"]
  timeout = 26

[functions."extract-prices-ai"]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
